name: Main
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        run: |
          COMMIT_MESSAGE="$(head -n 1 <<< "${{ github.event.head_commit.message }}")"
          echo COMMIT_MESSAGE="$COMMIT_MESSAGE" >> "$GITHUB_ENV"
          echo RELEASE_VERSION="${COMMIT_MESSAGE:16}" >> "$GITHUB_ENV"
      - name: Build
        run: make
      - name: Test
        run: make check
      - name: Tag
        run: |
          git tag "$RELEASE_VERSION"
          git push --tags
        if: "startsWith(github.event.head_commit.message, 'chore(release): ')"
  release:
    needs: build
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'chore(release): ')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        run: |
          COMMIT_MESSAGE="$(head -n 1 <<< "${{ github.event.head_commit.message }}")"
          echo COMMIT_MESSAGE="$COMMIT_MESSAGE" >> "$GITHUB_ENV"
          echo RELEASE_VERSION="${COMMIT_MESSAGE:16}" >> "$GITHUB_ENV"
      - name: Build
        run: make
      - name: Pack
        run: cd ./dist && tar -acf flightos-"$RELEASE_VERSION".tar.gz flightos
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/flightos-${{ env.RELEASE_VERSION }}.tar.gz
          generate_release_notes: true
