name: Main
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
      - name: Setup
        run: |
          COMMIT_MESSAGE="$(head -n 1 <<< "${{ github.event.head_commit.message }}")"
          echo COMMIT_MESSAGE="$COMMIT_MESSAGE" >> "$GITHUB_ENV"
          if grep -q '^chore(draft): ' <<< "$COMMIT_MESSAGE"; then
            echo RELEASE_VERSION="${COMMIT_MESSAGE:14}" >> "$GITHUB_ENV"
          elif grep -q '^chore(release): ' <<< "$COMMIT_MESSAGE"; then
            echo RELEASE_VERSION="${COMMIT_MESSAGE:16}" >> "$GITHUB_ENV"
          fi
      - name: Build
        run: make
      - name: Test
        run: make check
      - name: Tag
        run: |
          git config --global user.email 84666033+github-actions[bot]@users.noreply.github.com
          git config --global user.name github-actions[bot]
          make release ver="${{ env.RELEASE_VERSION }}"
        if: "startsWith(env.COMMIT_MESSAGE, 'chore(draft): ')"
      - name: Pack
        run: cd ./dist && tar -acf flightos-"$RELEASE_VERSION".tar.gz flightos
        if: startsWith(github.ref, 'refs/tags/')
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/flightos-${{ env.RELEASE_VERSION }}.tar.gz
          generate_release_notes: true
