name: Release
on:
  workflow_run:
    workflows:
      - Draft
    types:
      - completed
jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Setup
        run: |
          COMMIT_MESSAGE="$(git log --pretty=%B -1 | head -n 1)"
          echo RELEASE_VERSION="${COMMIT_MESSAGE:14}" >> "$GITHUB_ENV"
      - name: Build
        run: make
      - name: Pack
        run: cd ./dist && tar -acf flightos-"$RELEASE_VERSION".tar.gz flightos
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/flightos-${{ env.RELEASE_VERSION }}.tar.gz
          generate_release_notes: true
